### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by ISTIAKPAPPU** [poojatambe/Yolov5-inference-on-ONNXRuntime-and-opencv-DNN#1]
(onnxruntime) F:\ML_Unity\Yolov5-inference-on-ONNXRuntime-and-opencv-DNN>python yolov5_onnxinfer.py  --image 'bus.jpg'  --weights 'yolov5s.onnx' --conf_thres 0.7 --iou_thres 0.5 --imgs 640 --classes 'classes.txt
Namespace(classes="'classes.txt", conf_thres=0.7, image="'bus.jpg'", imgs=640, iou_thres=0.5, weights="'yolov5s.onnx'")
Traceback (most recent call last):
  File "yolov5_onnxinfer.py", line 290, in <module>
    ORT()
  File "yolov5_onnxinfer.py", line 24, in __call__
    image, ratio, dwdh = self.letterbox(image_or, auto=False)
  File "yolov5_onnxinfer.py", line 213, in letterbox
    shape = im.shape[:2]  # current shape [height, width]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by poojatambe** [comment]
Hi, thanks for reporting this issue. The command used to run the file is generating this error. 
Use this command: 
!python yolov5_onnxinfer.py  --image ./bus.jpg  --weights ./yolov5s.onnx --conf_thres 0.7 --iou_thres 0.5 --imgs 640 --classes ./classes.txt
You can refer README file for update.
